### ISSUE TITLE
[UNRELATED] Cannot Scan QR

### ISSUE THREAD

**Issue by reldyal** [JastinXyz/simple-portfolio#1]
![image](https://user-images.githubusercontent.com/87573334/189489798-b64fea70-d05e-470e-9e54-0b36b0cffda5.png)
When i scan the QR and his reconnected

**Comment by JastinXyz** [comment]
This is not a whatscode repository... you can visit the repository at https://github.com/JastinXyz/whatscode.js

don't use whatscode anymore for productive purposes, because the package is no longer actively maintained and maybe some functions can't be used. You can use another package like [@adiwajshing/baileys](https://npmjs.com/package/@adiwajshing/baileys)
